# Generated by Django 5.1.6 on 2025-02-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("inventory", models.IntegerField(default=5)),
            ],
            options={
                "verbose_name": "Menu",
                "verbose_name_plural": "Menu Items",
            },
        ),
        migrations.DeleteModel(
            name="MenuItem",
        ),
        migrations.AlterModelOptions(
            name="booking",
            options={
                "verbose_name": "Booking",
                "verbose_name_plural": "Booking Records",
            },
        ),
        migrations.RemoveField(
            model_name="booking",
            name="no_of_guests",
        ),
        migrations.AddField(
            model_name="booking",
            name="number_of_guests",
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name="booking",
            name="booking_date",
            field=models.DateTimeField(),
        ),
    ]
