# Generated by Django 5.1.6 on 2025-02-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_menu_delete_menuitem_alter_booking_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="number_of_guests",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="menu",
            name="inventory",
            field=models.IntegerField(),
        ),
    ]
